doc_source/reference_aws-services-that-work-with-iam.md

At least according to its documentation [here](https://docs.aws.amazon.com/singlesignon/latest/userguide/iam-auth-access-overview.html#accesscontrolresourcebased):
> Other services, such as Amazon S3, also support resource-based permissions policies. For example, you can attach a policy to an S3 bucket to manage access permissions to that bucket. AWS SSO doesn't support resource-based policies.
This change fixes the table to match the service's own documentation.

AWS SSO doesn't support resource-based policies

---

doc_source/id_roles_create_for-user_externalid.md

This seems wrong.  External IDs aren't secret, so it's reasonable to expect "Another AWS Account" in the example to know the "Your AWS Account" external ID provided by "Example Corp" in the AssumeRole request.

Word change: "know" to "control"

---

doc_source/reference_policies_elements_condition_operators.md

No issue. This is a trivial docs change.
There were two extraneous words in the docs explaining how IfExists condition operators work. More specifically, this change removes the string "the condition " from the docs.

Fixed wording for IfExists condition docs

---

doc_source/id_credentials_mfa_configure-api-require.md

The example talks about the two actions but `StopInstances` was repeated.

Fix repeated action name in API MFA example

---

doc_source/reference_aws-services-that-work-with-iam.md

As per Docs (and reality) AWS API Gateway supports resource based policies:
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies.html
Changed the flag from No to yes

API Gateway supports resource based policy

---

doc_source/list_amazonroute53autonaming.md

I think this should be `namespace` and not `stack`?
Change the resource type in the ARN example for service discovery

Set correct ARN in Resource Type format

---

doc_source/reference_policies_grammar.md

*Description of changes: The policy grammar is not valid. An equals sign is missing for the rule <condition_map>.*

An equals sign is missing in the policy grammar

---

doc_source/id_roles_use_switch-role-ec2.md

Swapped the principals in the trust policies for the example of an EC2 running with a role and allowing it to assume a role in another account.

Update EC2 cross account role trust policies example

---

doc_source/reference_policies_elements_principal.md

Typo
Fixed typo - singular to plural
**Before**: Some service role have
**After**: Some service roles have

Fix typo -- singular to plural

---

doc_source/id_roles_providers_enable-console-custom-url.md

*Description of changes:* The python code runs with an error because it's missing a carriage return between two lines of code. I see it running fine now with the lines properly separated.

missing a carriage return in the python sample

---

doc_source/reference_policies_iam-condition-keys.md

We learnt through a conversation with a AWS Premium Support that `iam:PassedToService` condition key is not supported by some AWS services. This change adds a note about the two services in the documentation.
It should help others running into similar problem.

Add a note about exceptions in `iam:PassedToService` condition key

---

doc_source/tutorial_attribute-based-access-control.md

as title, only in this line, qas is a value of the access-project tag instead of access-team

Change the key of `qas` from access-project to access-team

---

doc_source/tutorial_attribute-based-access-control.md

Issue
It is redirecting to IAM console link, it should redirect Sercetmanager's console link
Description of changes:
Just made the changes in the hyperlink from IAM console link to secretmanager console link

Changed the link for sercetmanager at line 215

---

doc_source/id_roles_providers_create_saml_assertions.md

*Description of changes:* Typo

Fix typo in TransitiveTagKeys attribute name

---

doc_source/id_session-tags.md

The session has tag `Heart` with value `1` (from the first assume-role), and the thing that fails is setting it to `3`.

Fix a tag value to make sense

---

doc_source/reference_policies_elements_principal.md

The original emphasized *user* entities being able to access the role, but ignored *role* entities.  
Also, originally failed to mention this being limited to accounts within the trusting account's aws partition.  So (e.g.) an aws-cn account can't trust a standard partition (aws) account.
Separately - calling this *Anonymous Users (Public)* seems kinda misleading, as it suggests that unauthenticated principals can use the role, which I don't think holds here.

Fix anonymous users description

---

doc_source/reference_policies_condition-keys.md

When trying to use ARN operators, you get an error back, but with string operators, it works.

Fix operators compatible with aws:PrincipalArn

---

doc_source/access_policies_managed-vs-inline.md

- Markdown bolding (removed space between `**` and text
- Fixed missing/invalid image references illustrating AWS Managed and Inline policies

Fixed type and image references

---

doc_source/cloudtrail-integration.md

*Description of changes:* Under "Example IAM API event in CloudTrail log file",`userIdentity.userName` should match the username in the `arn`: `JaneDoe` instead of `JameDoe`.

fix typo in event example

---

doc_source/reference_identifiers.md

Managed Policies do support specifying a Path through cloudformation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html

Updated iam-user-guide/reference_identifiers

---

doc_source/tutorial_billing.md

My web console just calls this "Account" not "My Account". Not sure when that changed or who it is changed for.

Fix text instruction

---

doc_source/reference_policies_iam-condition-keys.md

Simple Typo correction
Removed duplicate `.com.com` in the [Available keys for AWS web identity federation section](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#condition-keys-wif)
`cognito-identity.amazonaws.com.com:amr` should be `cognito-identity.amazonaws.com:amr` as shown on the next line

Fix Typo in reference_policies_iam-condition-keys.md 

---

doc_source/id_roles_providers_create_oidc_verify-thumbprint.md

*Issue #287*
Added "-sha1" parameter to the openssl command.

Specify that fingerprint from openssl command needs to be SHA1
