awsdocs/iam-user-guide

- doc_source/reference_aws-services-that-work-with-iam.md
https://docs.aws.amazon.com/cloudhsm/latest/userguide/create-iam-user.html
Not Applicable
CloudHSM does support Service-Linked roles https://docs.aws.amazon.com/cloudhsm/latest/userguide/create-iam-user.html
> CloudHSM supports service-linked roles

- doc_source/id_groups_manage_delete.md
Just added a missing word to fix *that attached* to *that are attached*.
> add missing word

- doc_source/id_roles_common-scenarios_aws-accounts.md
> Users can assume roles outside console

- doc_source/reference_policies_variables.md
> typo "allow"

- doc_source/reference_policies_actions-resources-contextkeys.md
In https://github.com/awsdocs/iam-user-guide/pull/83 I propose renaming this file. If This is Committed the link has to be changed.
> Correct Link for Pull Request 83

- doc_source/id_roles_common-scenarios_aws-accounts.md
The "principle of least access" should actually be "principle of least privilege".  Making this change for accuracy and for improved SEO.
> Principle of least privilege

- doc_source/console_search.md
Fixed search terms with inconsistent bold/strong attributes
> Fixed inconsistent bold

- doc_source/reference_policies_examples_s3_cognito-bucket.md
Fixing a typo in the change fixing #107.
> Removed extraneous slash in Cognito S3 bucket policy

- doc_source/id_roles_providers_enable-console-custom-url.md
Ported Custom Fed Broker Boto code to Boto3, made code tolerant of python 2 and 3
> Ported Custom Fed Broker Boto example code to Boto3, made code tolerant of python 2 and 3

- doc_source/reference_policies_examples_aws_my-sec-creds-self-manage.md
Noticed while copying to compare with our IAM user MFA policies
*Description of changes:* remove trailing whitespace from example code on two lines.
> Trailing whitespace in example JSON

- doc_source/list_awsconfig.md
> fix associated typo

- doc_source/id_roles_use_switch-role-ec2.md
*Description of changes:* Updating the SDK walkthrough links here - current links no longer exist, redirect to the top-level SDK page. Pretty sure these new links are correct.
> Update SDK walkthrough links

- doc_source/list_awsglue.md
The resource name for "devEndpoint" was incorrect, which causes IAM failures if implemented
> fix devEndpoint resource typo

- doc_source/reference_aws-services-that-work-with-iam.md
There is no resource-based policy for EFS.
> Set resource-based policy for EFS to no

- doc_source/reference_policies_examples_s3_cognito-bucket.md
> Added a note to clarify the sub value

- doc_source/reference_aws-services-that-work-with-iam.md
> Fixed reference for ECS as it was written as EC2

- doc_source/id_roles_create_for-service.md
It is just a simple fix for the Windows path for `aws iam` CLI command
> windows path

- doc_source/reference_policies_examples_aws_my-sec-creds-self-manage.md
N/A
Just removing a blank line.
> Remove pointless blank line in JSON policy document.

- doc_source/id_roles_create_for-idp.md
N/A
This is probably copy/paste mistake from other document about using MFA
> MFA is not related to web identity

- doc_source/id_tags.md
> Fix minor typos in id_tags.md

- doc_source/reference_identifiers.md
> Fix typo in reference_identifiers.md

- doc_source/resource_examples_iam_policies_resource_account.md
The format in the example seems not correct. I added back a missing `]`.
> Improve format and add back missing square bracket

- doc_source/id_root-user.md
Changing "My Security Credentials" -> "Security credentials" so that guide reflects latest UI
> Update copy to reflect latest UI
